version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sos360-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sos360
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sos360-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d sos360']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sos360-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3002
      API_VERSION: v1
      APP_NAME: SOS360-API
      DATABASE_URL: postgresql://user:password@postgres:5432/sos360?schema=public
    env_file:
      - .env.docker
    ports:
      - '3002:3002'
    networks:
      - sos360-network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  sos360-network:
    driver: bridge
